/*
 * Auto-generated by Frida. Please modify to match the signature of recv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`recv(sockfd=${args[0]}, buf=${args[1]}, len=${args[2]}, flags=${args[3]})`);
    try {
      try {
        Java.perform(function () {
          try {
            var Thread = Java.use('java.lang.Thread');
            var cur = Thread.currentThread();
            var st = cur.getStackTrace();
            var javaFrames = [];
            for (var i = 0; i < st.length; i++) {
              try { javaFrames.push(st[i].toString()); } catch (ee) {}
            }
            if (javaFrames.length > 0) {
              log("JAVA STACK")
              for(let i = 0;i<javaFrames.length;i++){
                    log((i+1)+") "+javaFrames[i])
              }
              log("\n");
            }
          } catch (je) {
            
          }
        });
      } catch (e) {
        
      }
    } catch (err) {
      log('[connect.enter] handler error: ' + err);
    }
  },

  onLeave(log, retval, state) {
  }
});
